/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package paralelo

import org.scalatest.funsuite.AnyFunSuite
import org.junit.runner.RunWith
import org.scalatestplus.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class MergeSortTest extends AnyFunSuite {
  test("MergeSortTest") {
        val mergeSort = new MergeSort()
        val v1 = Vector(10,9,7,8,6,5,4,3,1,2)
        val v2 = Vector(1,2,3,4,5,6,7,8,9,10)
        assert(mergeSort.mergeSortSeq(v1) == v2)
      }
    
    

}
