/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package power

object App {
 
  def power(x:Double,p:Double): Double =  {
    Math.pow(x,p)

  }
  //SumaSegmento
  def SumaSegmento(A:List[Int],p:Double,t:Int,s:Int):Double = {
    var sum:Double = 0.0

    for (i <- t to s) {
      sum += power(A(i),p)
    }
    power(sum,1/p)
  }

  def SumaSegmentoP2(A:List[Int],p:Double):Double = {
    val m:Int = A.length/2
    val (p1,p2) = (SumaSegmento(A,p,0,m),SumaSegmento(A,p,m+1,A.length-1))
    power(p1+p2,1/p)

  }

  def main(args: Array[String]): Unit = {
    val l = List(1,2,3,4,5,6,7,8,9,10) // n(n+1)(2n+1)/6

    println(SumaSegmento(l,2.0,0,l.length-1))
    println(SumaSegmentoP2(l,2.0))
    

  }
}  
